spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/social_authorization
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    refreshToken: XBsL1lb59hAFi4C2VPtYXk4pSf8F7kcH3jGu8s92oIwlpWGzYBXXsRGOjiKHyy9rq3ul4s
